internal/lagoon/tasks.go
Ensures that we don't exec into pods that are in the process of being deleted
=> Fixes issue with execing into pods scheduled for deletion

cmd/root.go, cmd/validate_compose.go
Made a flag global and changed the way errors are displayed if found
=> Minor fixes for docker-compose validation cmd

internal/generator/backups.go, internal/generator/backups_test.go
If the `K8UP_WEEKLY_RANDOM_FEATURE_FLAG` is defined, but not set to `enabled`, we should use the default values for `check` and `prune` schedules as there is no other override for these.
=> fix: use the default value is the override is not enabled

internal/generator/generator.go, internal/helpers/helpers_dbaas.go, internal/helpers/helpers_dbaas_test.go
Unless an alternative is provided, set http as the default for the dbaas-operator endpoint
=> use http for dbaas-operator endpoint

cmd/tasks_run.go, cmd/tasks_run_test.go, internal/generator/buildvalues.go, internal/generator/generator.go, internal/lagoon/tasks.go
This increases the default wait time from 3 to 10 seconds between iterations, and increases the iterations to 30 from 10.
It also adds two variables that can be added to a `remote-controller` deployment:
* `LAGOON_FEATURE_FLAG_TASK_SCALE_MAX_ITERATIONS` (integer)
* `LAGOON_FEATURE_FLAG_TASK_SCALE_WAIT_TIME` (integer)
closes #83
=> Feature: Configurable scaling options

.github/workflows/docker-image.yaml
As per https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit this PR checks out the PR head instead of the merge commit, ensuring that the ref in the build commit is correct.
=> Use pr-branch only checkout to maintain the git ref for PRs

legacy/docker-entrypoint.sh
After the introduction of network policies in `lagoon-remote` on the docker-host, there is a race condition where the network policy hasn't applied fully before the pod has started. This results in the docker-host check failing.
To fix this, the build should try connect to the docker-host a few times before failing.
=> try connect to docker-host a few times

legacy/build-deploy-docker-compose.sh
The intent here is to allow the remote-controller to set an environment variable on the build pod which will control the memory limit set on containers deployed by Lagoon.
This single memory limit value would be set via a flag in the remote-controller, so it would apply to _all_ containers deployed by Lagoon.
See https://github.com/uselagoon/remote-controller/pull/169 for the associated remote-controller PR.
=> feat: add support for default lagoon container memory limits

legacy/build-deploy-docker-compose.sh, legacy/scripts/exec-build.sh
As documented in https://docs.docker.com/engine/reference/commandline/build/#specifying-target-build-stage---target and https://docs.docker.com/compose/compose-file/build/#target developers can specify individual build-stages within a dockerfile to build a specific service from. This is particularly useful when building with concurrency (as in Buildkit)
This PR adds that functionality to the build-deploy-tool, and is triggered on receiving the `target` setting as part of the build section in a service.
closes #108
=> add BUILD_TARGET logic to legacy docker build

legacy/build-deploy-docker-compose.sh
https://github.com/uselagoon/lagoon/issues/2246 raised the question of adding randomization in a build arg in order to break caching. This PR (at the suggestion of @tobybellwood ) injects the build pod's hostname (which is unique) as the variable `LAGOON_BUILD_NAME`.
=> Feature: Add LAGOON_BUILD_NAME to BUILD_ARGS

legacy/helmcharts/postgres-single/templates/deployment.yaml
`mariadb-dbaas` and `mariadb-single` both use mysqldump to produce backups
`postgres-dbaas` does pg_dump, but `postgres-single` backs up the data volume, which doesn't seem very useful in terms of being able to easily move to another database.
This brings `postgres-single` in line to use pg_dump like `postgres-dbaas`.
Unfortunately, this would mean that backups from after users deploy after this change would have a different type of backup file to restore with. But I hope this would be a welcome change for people to be able to easily restore from.
=> Change: use pg_dump for postgres-single

internal/lagoon/tasks.go, legacy/build-deploy.sh
In kubernetes 1.24, service accounts no longer get automatically generated token secrets. It is possible to generate long lived tokens, but using the TokenRequest API is the recommended way forward.
The remote-controller will now use the serviceaccount on all pods started by it, which uses volume projection to mount the token into the pod automatically.
The default will be to try the existing token location, but if one has been provided the service account, it will use this this.
=> chore: support consuming deployer-token from service account

legacy/helmcharts/basic-persistent/templates/cronjob.yaml, legacy/helmcharts/basic/templates/cronjob.yaml, legacy/helmcharts/cli-persistent/templates/cronjob.yaml, legacy/helmcharts/cli/templates/cronjob.yaml, legacy/helmcharts/elasticsearch/templates/cronjob.yaml, legacy/helmcharts/kibana/templates/cronjob.yaml, legacy/helmcharts/logstash/templates/cronjob.yaml, legacy/helmcharts/mariadb-single/templates/cronjob.yaml, legacy/helmcharts/mongodb-single/templates/cronjob.yaml, legacy/helmcharts/nginx-php-persistent/templates/cronjob.yaml, legacy/helmcharts/nginx-php/templates/cronjob.yaml, legacy/helmcharts/nginx/templates/cronjob.yaml, legacy/helmcharts/node-persistent/templates/cronjob.yaml, legacy/helmcharts/node/templates/cronjob.yaml, legacy/helmcharts/opensearch/templates/cronjob.yaml, legacy/helmcharts/postgres-single/templates/cronjob.yaml, legacy/helmcharts/python-persistent/templates/cronjob.yaml, legacy/helmcharts/python/templates/cronjob.yaml, legacy/helmcharts/rabbitmq/templates/cronjob.yaml, legacy/helmcharts/redis-persistent/templates/cronjob.yaml, legacy/helmcharts/redis/templates/cronjob.yaml, legacy/helmcharts/solr/templates/cronjob.yaml, legacy/helmcharts/varnish-persistent/templates/cronjob.yaml, legacy/helmcharts/varnish/templates/cronjob.yaml, legacy/helmcharts/worker-persistent/templates/cronjob.yaml, legacy/helmcharts/worker/templates/cronjob.yaml
There is an issue with cronjob templates where filling out the affinity, nodeselector, or tolerations will fail. This corrects the templating issues.
=> fix: cronjob templates

legacy/helmcharts/postgres-single/templates/deployment.yaml
[This playground shows the fix](https://repeatit.io/#/share/eyJ0ZW1wbGF0ZSI6Int7IHJlZ2V4UmVwbGFjZUFsbCBcIlxcXFxXK1wiIC5SZWxlYXNlLk5hbWUgXCJfXCIgfCB1cHBlciB9fSIsImlucHV0IjoiUmVsZWFzZTpcbiAgTmFtZTogcG9zdGdyZXMtZGF0YXN0b3JlIiwiY29uZmlnIjp7InRlbXBsYXRlIjoidGV4dCIsImZ1bGxTY3JlZW5IVE1MIjpmYWxzZSwiZnVuY3Rpb25zIjpbInNwcmlnIl0sIm9wdGlvbnMiOlsibGl2ZSJdLCJpbnB1dFR5cGUiOiJ5YW1sIn19)
Running the template command against it (`helm template postgres-datastore legacy/helmcharts/postgres-single/`), it renders correctly: 
```
k8up.syn.tools/backupcommand: /bin/sh -c "PGPASSWORD=$POSTGRES_DATASTORE_PASSWORD pg_dump --host=localhost --port=$POSTGRES_DATASTORE_SERVICE_PORT --dbname=$POSTGRES_DATASTORE_DB --username=$POSTGRES_DATASTORE_USER --format=t -w"
```
closes #150
=> fix: replace special chars with underscore for postgres-single backups

legacy/helmcharts/nginx-php-persistent/values.yaml, legacy/helmcharts/nginx-php/values.yaml, legacy/helmcharts/node-persistent/values.yaml, legacy/helmcharts/node/values.yaml
Empirical evidence suggests that the median memory usage for php and node is much closer to 100Mi than 10Mi.
=> feat: bump memory requests for node and php charts

internal/generator/services.go, internal/generator/services_test.go
The current error response for builds with no Lagoon type set is quite generic - e.g. `Rollout for ${SERVICE_NAME} failed, tried to gather some startup logs of the containers, but unfortunately there were none created, sorry.`
This provides a more verbose error message when no Lagoon type is set.
=> Error msg for builds without a Lagoon type

Dockerfile
This PR updates the version of Alpine in use to 3.17
This also updates the version of git to cover the most recent disclosed CVEs
2.38.3-r0:
- CVE-2022-41903
- CVE-2022-23521
=> update Alpine version to 3.17 via docker image

Dockerfile, cmd/validate_lagoonyml.go, cmd/validate_lagoonyml_test.go, internal/lagoon/lagoon.go, legacy/build-deploy-docker-compose.sh, test-resources/validate-lagoon-yml/cronjobs/lagoon-override-env.yml, test-resources/validate-lagoon-yml/cronjobs/lagoon-override.yml, test-resources/validate-lagoon-yml/cronjobs/lagoon.yml, test-resources/validate-lagoon-yml/cronjobs/multiline-cronjobs.lagoon.yml, test-resources/validate-lagoon-yml/cronjobs/singleline-cronjobs.lagoon.yml
Part of https://github.com/uselagoon/build-deploy-tool/issues/103
Copies the cronjob validation from [lagoon-linter](https://github.com/uselagoon/lagoon-linter) into the `validate lagoon-yml` command and runs validation at the start of every build.
Updates lagoon-linter to v0.8.0.
=> feat: add validation for multiline cron jobs and validate at start of build

internal/lagoon/routes.go, internal/templating/ingress/templates_ingress_test.go, internal/templating/ingress/test-resources/result-custom-ingress4.yaml, internal/templating/ingress/test-resources/result-custom-ingress5.yaml, test-resources/identify-ingress/test16/lagoon.yml, test-resources/template-autogenerated/test20/lagoon.yml, test-resources/template-ingress/test11/lagoon.yml
Sets HSTS `max-age` to 1 year. Removes deprecated `hsts` from test `.lagoon.yml` files.
Closes #188
=> fix: set HSTS max-age to be 1 year by default

Dockerfile
in #164 we needed to pin the OpenSSH version to avoid an Alpine package resolution error - once this PR passes tests, we should merge it to remove that pin.
The conflict is caused by the upstream docker/20.10.22 image already having an older version of some OpenSSH libraries installed. These libraries have been updated in the Alpine package registry. Our attempt to install a newer version of the parent OpenSSH package, therefore, causes conflicts.
This PR, therefore, installs and upgrades all the OpenSSH libraries and packages in a single step.
=> revert openssh 9.1_p1-r2 pinning

legacy/build-deploy-docker-compose.sh
This moves the check for pre and post rollout task disabling outside of an if statement that prevent promote environments from using it
=> fix: move the pre and post rollout variable check to allow promote

legacy/build-deploy.sh
Small refactor to the way the service account token is determined. This falls back to the older deployer token that was created prior to kubernetes 1.24, and prefers the service account token that is generated on demand by the build pods.
This reduces the possibility of the following warning appearing in build logs causing confusion
```
Warning: Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
```
=> refactor: prefer the service account token over the older deployer token

legacy/build-deploy.sh
Adds a missing `fi` to an if statement in the service account token check step
=> fix: add missing closing fi to if

legacy/build-deploy-docker-compose.sh
Just a minor change to patch the build at the beginning of the build step, rather than at the end.
This also means that the current stage of the build will be present in the build logs, unlike the current state where it only updates when the step is complete. This will make it clearer which stage the build is at.
This should also help with reducing the race condition of the final two messages by not patching the build at the very end when the completion is also being sent
=> refactor: patch at the start of the step, rather than the end

cmd/tasks_run.go, cmd/tasks_run_test.go, internal/lagoon/tasks.go, legacy/build-deploy-docker-compose.sh
=> refactor: combined task output to single stream to retain order

legacy/build-deploy-docker-compose.sh
Fixes an error introduced in #241 where attempting to cleanup tls certificates for an ingress that already doesn't have any tls certificates will fail the build.
The build failure error is: `jq: error (at <stdin>:175): Cannot iterate over null (null)` which is thrown at https://github.com/uselagoon/build-deploy-tool/blob/main/legacy/build-deploy-docker-compose.sh#L1769. The `jq` sequence includes `.spec.tls[]` which is not guaranteed to exist.
The fix is to use `[]?` to make `jq` treat it as optional.
Example ingress with a secret that needs to be cleaned
```
{
"ingressClassName": "nginx",
"rules": [
{
"host": "redacted",
"http": {
"paths": [
{
"backend": {
"service": {
"name": "nginx",
"port": {
"name": "http"
}
}
},
"path": "/",
"pathType": "Prefix"
}
]
}
}
],
"tls": [
{
"hosts": [ …
```
=> fix: tls cleanup error on ingress with no tls

internal/templating/backups/template_prebackuppod.go, internal/templating/backups/test-resources/result-prebackuppod3.yaml
Just a small fix to the variable name for username in the backup command
=> fix: use correct username in backup command for mongo prebackuppod

internal/templating/backups/template_prebackuppod.go, internal/templating/backups/test-resources/result-prebackuppod3.yaml
Just minor work to add the other missing variables for mongo prebackuppods. These aren't actually used by the backup command, but they may get used in the future.
Fixes the backup command to also support mongodb and documentdb backups and dumps the archive which can be restored using `mongorestore`
=> chore: add other missing values for mongo prebackuppods

legacy/build-deploy-docker-compose.sh
The step where the service is created didn't know about the port change capabilities of the `basic` service type. This fixes it so that it will set the override if it is set.
=> fix: basic service port override when the service is set

legacy/build-deploy.sh
This adds a username override key to internal container registry login in a similar manner to how #132 allowed for the password to be overridden.
Given the following container-registries block, and wanting to change the username for the account defined from `robot$robotic` to something else, you can add a project or environment variable of the scope `container_registry` with the name `REGISTRY_my-harbor_USERNAME` and set it to whichever username it should be instead.
```
container-registries:
my-harbor:
username: robot$robotic
password: my-special-password
url: harbor.example.com
```
With a verify script https://gist.github.com/shreddedbacon/892f8206282aed54c029ed1979b6fcb6
=> refactor: add a check for username override key variable from api

legacy/helmcharts/nginx-php-persistent/templates/_helpers.tpl, legacy/helmcharts/nginx-php-persistent/templates/deployment.yaml, legacy/helmcharts/nginx-php-persistent/values.yaml, legacy/helmcharts/nginx-php/templates/_helpers.tpl, legacy/helmcharts/nginx-php/templates/deployment.yaml, legacy/helmcharts/nginx-php/values.yaml
Just a fix that allows for the resources that get defined by overrides (like container memory limits) to get applied to nginx-php based templates, which didn't happen before because they had container specific definitions that meant the overrides never got applied.
=> fix: resource overrides in nginx-php templates

cmd/template_backups_test.go, internal/generator/generator.go, test-resources/template-backups/test1-results/k8up-lagoon-backup-schedule.yaml, test-resources/template-backups/test2-results/k8up-lagoon-backup-schedule.yaml, test-resources/template-backups/test3-results/k8up-lagoon-backup-schedule.yaml, test-resources/template-backups/test4-results/k8up-lagoon-backup-schedule.yaml, test-resources/template-backups/test5-results/k8up-lagoon-backup-schedule.yaml, test-resources/template-backups/test6-results/k8up-lagoon-backup-schedule.yaml
Fix to actually source the namespace from the build for use in templating backup schedules. Backup schedules are the only part of a build step in the tool that actually uses the namespace currently.
=> fix: actually source the namespace

.github/workflows/docker-image.yaml
This would allow us to create `release/*` branches, then we can build PR images for hotfixes against a particular release tag/version
=> chore: allow images merging against a release branch to build images

legacy/build-deploy-docker-compose.sh
An error was introduced in #265 due to invalid `base64` flag:
```
base64: unrecognized option: decode
BusyBox v1.36.0 (2023-05-05 06:41:49 UTC) multi-call binary.
Usage: base64 [-d] [-w COL] [FILE]
Base64 encode or decode FILE to standard output
-d	Decode data
-w COL	Wrap lines at COL (default 76, 0 disables)
```
This PR removes the call to `base64` altogether in favor of `jq`. Tested in a live `build-deploy-tool` pod.
=> fix: dioscuri migration uses invalid base64 decode flag

internal/generator/generator.go, internal/helpers/helpers.go, internal/helpers/helpers_test.go, internal/helpers/test-resources/test2
Just a fix up from #275 to source the namespace from the service account file if one is found
=> refactor: namespace sourcing from the serviceaccount file if found

cmd/tasks_run.go, cmd/tasks_run_test.go
Just removing the duplicated namespace calculation step from the tasks runner to use the value that comes from the generator output now that #278 is merged and resolves the namespace being provided to the generator.
=> refactor: remove the duplicated namespace calculation for the generator value

cmd/template_backups_test.go, internal/generator/backups.go, internal/generator/backups_test.go, internal/generator/buildvalues.go, internal/generator/generator.go, internal/helpers/helpers_cron.go, internal/helpers/helpers_cron_test.go, test-resources/template-backups/test7-results/k8up-lagoon-backup-schedule.yaml, test-resources/template-backups/test7/docker-compose.yml, test-resources/template-backups/test7/lagoon.yml
Minor adjustment to the cron generator to account for interval based hourly times (H/6 or */6, etc) and to correctly consume the `DEFAULT_BACKUP_SCHEDULE` variable from remote-controller injected variable
=> fix: cron generator to support hourly interval and default backup schedule variable

Dockerfile, legacy/scripts/exec-generate-insights-configmap.sh
As it stands, we're using trivy as the sbom scanner in insights-handler, but generating sboms with `syft` on the remote side.
This has lead to issues with format incompatibilities across the two tools - specifically, an [update to the cyclonedx format ](https://github.com/CycloneDX/cyclonedx-go/releases/tag/v0.8.0) wasn't tracked in both tools and lead to a [fatal crash](https://github.com/uselagoon/insights-handler/pull/60)  in the handler.
This brings the insights generation in line, tooling wise, by replacing grype with trivy for sbom generation.
=> Replace grype with trivy for cyclonedx generation

legacy/build-deploy-docker-compose.sh
Just a quick one to make the warning message when a route cleanup detection event is encountered.
This hopefully makes it clear if a user has configured the route cleanup feature flag and its usage, that route cleanup may be automatic in the future, and that the user can correct the issue themselves if they need to by either fixing their lagoon.yml or adding the clean up variable.
Now the user will see one of two warnings, if they have routes that can be cleaned up
```
>> Lagoon detected routes that have been removed from the .lagoon.yml or Lagoon API
> If you need these routes, you should update your .lagoon.yml file and make sure the routes exist.
> You can remove these in the next build by setting the flag 'LAGOON_FEATURE_FLAG_CLEANUP_REMOVED_LAGOON_ROUTES=enabled' as a GLOBAL scoped …
```
=> refactor: make warning message clearer for route cleanup

legacy/scripts/exec-generate-insights-configmap.sh
Currently the insights image is fixed in the `exec-generate-insights-configmap.sh` file - this PR:
- makes use of the globally set IMAGECACHE_REGISTRY env var to set an image cache
- introduces INSIGHTS_SCAN_IMAGE env var to allow overriding of the image used to run the scan
=> Adds ability to control insights scan image with env vars

legacy/scripts/exec-kubectl-mariadb-dbaas.sh, legacy/scripts/exec-kubectl-mongodb-dbaas.sh, legacy/scripts/exec-kubectl-postgres-dbaas.sh
This adds a message that the consumer failed to provision if the failure annotation is found on a resource.
Ideally this would point to some troubleshooting steps somewhere, but these do not exist at the moment.
Pushing this PR for now while working on troubleshooting steps. Developers can't really do this investigation as the error is with the dbaas-operator somewhere, and exposing the error message from the dbaas-operator is probably not the best idea.
=> change: improve message and fail sooner on failure to provision dbaas

legacy/build-deploy-docker-compose.sh
Just extends the build to clean up any storage calculator pods before resources are applied to prevent blocking deployments of workloads.
closes #293
=> fix: remove any storage calculator pods during a build

legacy/helmcharts/postgres-single/templates/deployment.yaml
Just a quick fix identified through general testing.
The previous backup command for `postgres-single` used a username and password derived from the service name, which is not correct. Only the port can be derived this way due to `enableServiceLinks` which creates the port from the service name. The other variables are defined within the lagoon provided base images.
=> fix: postgres-single backup command use correct variables

legacy/build-deploy-docker-compose.sh
In combination with https://github.com/uselagoon/lagoon/pull/3638, this fixes the behaviour of when `tls-acme: true` is changed to `false` so that it also correctly cleans up the certificate being served.
closes #290
=> fix: remove the secret when tls-acme is set to false

legacy/build-deploy-docker-compose.sh
This adds an accordion that will present any ingress that have stale acme challenges. The accordion will only display if any are detected.
I've linked to the going-live documentation, but this could probably be better placed in its own section along with build errors and warnings maybe?
```
>> Lagoon detected routes that have stale acme certificate challenges.
This indicates that the routes have not generated the certificate for some reason.
You may need to verify that the DNS or configuration is correct for the hosting provider.
https://docs.lagoon.sh/using-lagoon-the-basics/going-live/#routes-ssl
Depending on your going live instructions from your hosting provider, you may need to make adjustments to your .lagoon.yml file
Otherwise, If you no longer need these routes, you should remove …
```
=> feat: warn if old certificate challenges are present

legacy/scripts/exec-generate-insights-configmap.sh
This adds an explicit label used for typing insights ConfigMap data.
It essentially duplicates the data that is currently in the `lagoon.sh/insightsType` label, but brings it in line with [this proposal](https://github.com/uselagoon/lagoon/issues/3597).
Furthermore, by dropping the `-gz` designation in the type, we are pointing towards the proposed introduction of [stricter types for insights-remote](https://github.com/uselagoon/insights-remote/issues/19). With regards to this, note how the new `insights.lagoon.sh/type` does not reference whether the data is compressed or not - this acknowledges that we will only process compressed binary data for `sbom` and `inspect` types going forward.
=> refactor: use new insights.lagoon.sh/type label

cmd/template_dbaas_test.go, internal/testdata/complex/dbaas-templates/dbaas-4/dbaas.yaml, internal/testdata/complex/docker-compose.services.yml, internal/testdata/complex/lagoon.services.yml, legacy/build-deploy-docker-compose.sh
Just refactoring the meta service check for when just `mariadb`, `postgres`, or `mongo` are requested.
The move to go in #115 didn't fully convert the meta checks as some things still take place in BASH for generating the `-single` versions of these types.
=> refactor: dbaas meta service check

legacy/helmcharts/redis-persistent/templates/deployment.yaml
#314 set the timeout to 14400 (4hrs) but this may be too long
This lowers it to 1.5hrs. Acknowledging this is pretty hacky solution generally. But if a redis-persistent is taking longer than this to backup, you probably shouldn't be using redis-persistent in a pod.
=> chore: lower timeout to 1.5hr for redis-persist backup

legacy/build-deploy.sh
Just a quick refactor on the existing variables to allow them to be used without having to define `username` or `password` in the `.lagoon.yml` at all.
[Validation gist](https://gist.github.com/shreddedbacon/25ee93cc4bee89e4510ae0173892eb3d)
=> refactor: lagoon.yml container-registry variable override checks

.github/workflows/docker-image.yaml, .github/workflows/lagoon-core-docker-image.yaml, Dockerfile
This PR modifies the dockerfile build process to account for ARM-based systems - either locally or in-cluster
=> build: initial multiarch commit

legacy/build-deploy.sh
shyaml is not great and we should stop using it. As more and more work goes into #289 the usage of shyaml is reduced significantly though.
This changes the checks to use `yq` where possible in the container-registry functions to handle things shyaml isn't great with.
The version of `yq` used is `v4.35.2` which is what is used in the build-deploy-image currently
With updated [gist](https://gist.github.com/shreddedbacon/25ee93cc4bee89e4510ae0173892eb3d) 
#310 introduced the changed logic, but the version of shyaml differs across operating systems and some handled it differently.
=> fix: use yq for checking container-registries because shyaml is not great

legacy/build-deploy-docker-compose.sh
Just a small fix to a date check since date in busybox is limited. Replaces it with awk to regex anything greater than 60m/1h instead.
Currently when this process runs, it results in this in the output which can be confusing to users.
```
date: invalid date '1 hour ago'
date: invalid date '2024-05-27T08:53:43Z'
```
This fix also nullifies error output if there are no ingress in the namespace (which is the case majority of the time)
=> fix: tls-acme stale challenge check to not use busybox date

legacy/build-deploy-docker-compose.sh
In cases where `tls-acme` is changed from true to false, and a certificate cleanup is required, the step that would check the certificate to see if it was a Let's Encrypt certificate would fail due to the following base64 decode error inside a build pod.
```
>> Cleaning up certificate for example.com-tls as tls-acme is set to false
base64: unrecognized option: decode
```
Initially introduced in #291, this changes the base64 decode to use the one built into JQ like other commands in the bash script do. Also removes an errant `s` in the grep.
=> fix: use jq base64d and remove errant s in cert cleanup

internal/templating/backups/template_prebackuppod.go, internal/templating/backups/test-resources/result-prebackuppod1.yaml, internal/templating/backups/test-resources/result-prebackuppod4.yaml, internal/templating/backups/test-resources/result-prebackuppod5.yaml, internal/testdata/complex/backup-templates/backup-1/prebackuppods.yaml, internal/testdata/complex/backup-templates/backup-2/prebackuppods.yaml, legacy/helmcharts/mariadb-single/templates/deployment.yaml
Based on discussion in #323 this just sets the max-allowed-packet to be the maximum supported.
closes #323
=> chore: increase max-allowed-packet in mysql backup cmds

cmd/identify_imagebuild_test.go, internal/generator/build_data.go, internal/generator/buildvalues.go, internal/generator/generator.go, internal/testdata/testdata.go, legacy/build-deploy-docker-compose.sh
This PR restores the LAGOON_CACHE_  functionality into the correct place in the build to allow the ARGS to be used
=> fix: add LAGOON_CACHE_ build arg support back

.github/workflows/build.yaml, .github/workflows/docker-image.yaml, .github/workflows/test.yaml
This PR introduces go and docker caching into the github actions.
In addition, there is now docker layer caching available, so the non-golang layers will also be cached, which can speed up the builds from 12 to 10 minutes.
It uses a hash of go.mod - so if no golang changes are made, the cache is available to the build to use, which can speed up builds from 10 to 2 minutes.
=> build: add gha cache for go and docker

internal/generator/services.go, internal/testdata/complex/service-templates/service1/deployment-nginx-php.yaml, internal/testdata/complex/service-templates/service2/deployment-nginx-php.yaml
Fix the check for adding replicas for production environments when spot is enabled
=> fix: check usespot before applying replicas

cmd/template_lagoonservices_test.go, internal/lagoon/lagoon.go, internal/lagoon/lagoon_test.go, internal/lagoon/test-resources/lagoon-yaml/test9/lagoon.yml, internal/testdata/basic/lagoon.polysite-cronjobs.yml, internal/testdata/basic/service-templates/service7/cronjob-cronjob-node-some-other-drush-cron.yaml, internal/testdata/basic/service-templates/service7/deployment-node.yaml, internal/testdata/basic/service-templates/service7/service-node.yaml
Polysite cronjob inheritence was broken in the lagoon yaml processor.
This fixes it so that if a polysite project has cronjobs defined, it will still inherit the `environments.$env.cronjobs` and merge them onto the `$project.environments.$env.cronjobs`
Added and updated tests to include this processor for cronjobs on polysites in the lagoon yaml processor
=> fix: polysite cronjob inheritence from lagoon yaml

internal/helpers/helpers_cron.go, internal/helpers/helpers_cron_test.go
The old crontab generator just passed through values for day and month: https://github.com/uselagoon/build-deploy-tool/blob/a4fc0b326fc144b3f17653d7a1da570ad43a900d/legacy/scripts/convert-crontab.sh#L90-L95 while the new cron validates them.
Some values were not included in the validations, this PR addresses those.
http://man.he.net/man5/crontab
```
```
=> fix: more supported cron values

internal/templating/services/templates_cronjob.go, internal/templating/services/templates_cronjob_test.go, internal/templating/services/test-resources/cronjob/result-cli-2.yaml
Deployments already include the fsGroupChangePolicy OnRootMismatch when
enabled. Cron jobs that use the same volumes also need this policy set
to speed up pod startup. This is especially helpful when a volume contains
a large amount of files.
=> chore: Add fsGroupChangePolicy to cron jobs

internal/servicetypes/elasticsearch.go, internal/templating/services/test-resources/deployment/result-elasticsearch-1.yaml, internal/templating/services/test-resources/pvc/result-elasticsearch-1.yaml, internal/templating/services/test-resources/service/result-elasticsearch-1.yaml
Fixes an issue with the template being `elasticsearch-persistent` instead of just `elasticsearch`
=> fix: elasticsearch is actually elasticsearch-persistent

internal/servicetypes/nginx.go, internal/templating/services/test-resources/deployment/result-nginx-1.yaml, internal/templating/services/test-resources/deployment/result-nginx-2.yaml, internal/testdata/complex/service-templates/service1/deployment-nginx-php.yaml, internal/testdata/complex/service-templates/service2/deployment-nginx-php.yaml, internal/testdata/complex/service-templates/service5/deployment-nginx-php.yaml, internal/testdata/complex/service-templates/service6/deployment-nginx-php.yaml
This introduces the port name "php" for the additional PHP container.
Using the same port name twice can lead to situations where a service
pointing to a named port would route the traffic to the wrong container.
=> fix: Use distinct container port names

cmd/identify_imagebuild.go, cmd/identify_imagebuild_test.go, go.mod, go.sum, internal/generator/buildvalues.go, internal/generator/services.go, internal/generator/services_test.go, internal/testdata/basic/docker-compose.forcebaseimagepull.yml, internal/testdata/basic/lagoon.forcebaseimagepull.yml, legacy/build-deploy-docker-compose.sh
Currently, if one chooses to implement a base image solution -- that is, most of one's code being bundled in an upstream image shared by multiple projects/environments -- there is an issue with caching.
If the base image, say, `container.reg/my/baseimage:latest`, or indeed, anything that isn't injected explicitly into the build, the image is cached by the docker-host, and if you make changes to the upstream image, but `container.reg/my/baseimage:latest` is currently _in_ the docker-host's cache, it's not going to pull the new upstream image.
This small change allows users to explicitly mark their services as using a base image, and specifying what the name of that image is via an optional label `lagoon.base.image`.
This leads to, for example, service definitions that look like so:
``` …
```
=> Feature - specify base images to refresh on deploy

internal/templating/services/templates_cronjob.go, internal/templating/services/test-resources/cronjob/result-cli-1.yaml, internal/templating/services/test-resources/cronjob/result-cli-2.yaml, internal/testdata/complex/service-templates/service1/cronjob-cronjob-cli-drush-cron2.yaml, internal/testdata/complex/service-templates/service2/cronjob-cronjob-cli-drush-cron2.yaml, internal/testdata/complex/service-templates/service5/cronjob-cronjob-cli-drush-cron2.yaml, internal/testdata/complex/service-templates/service6/cronjob-cronjob-cli-drush-cron2.yaml
Due to the way builds apply templates, removing a label is not enough
In https://github.com/uselagoon/build-deploy-tool/commit/fb6924b5e389f9cbabde43f953675be95f0fad61 we removed the label from being set, but in old cronjobs this left the label in place. New cronjobs were not impacted though as they would never have the label.
This changes the behaviour to prefix the labels that would have been set with `cronjob-` so that the values are there, but are not the same as what a deployment would have to prevent them from being counted towards the deployment pods when being selected by SSH services
=> fix: add labels back to cronjobs with a prefix

cmd/template_lagoonservices_test.go, internal/generator/services.go, internal/lagoon/lagoon.go, internal/lagoon/lagoon_test.go, internal/lagoon/test-resources/lagoon-yaml/test10/lagoon.yml, internal/testdata/basic/lagoon-cronjob-native-disable.yml, internal/testdata/basic/service-templates/service8/deployment-node.yaml, internal/testdata/basic/service-templates/service8/service-node.yaml
In some cases, a cronjob that would typically be run as a native kuberentes `CronJob` type may be better to run within the pod of the service directly. Since the in pod and native kubernetes switch is based on the interval of the cronjob, there is no way to do this without increasing the frequency of the cronjob, or writing a wrapper around the cronjob.
This offers a simple way to tell a cronjob to run in the service pod instead of a kubernetes native `CronJob` by way of an `inPod` field.
Set this to `true`, and the pod will be converted to an in pod cronjob:
```
- name: my special cronjob
schedule: "45 * * * *"
command: example cronjob command
service: cli
inPod: true
```
=> feat: override to be able to force cronjob into service pod

legacy/build-deploy-docker-compose.sh
This adds the ability for builds to report images that have been marked as deprecated by Lagoon, and surface suggested replacements.
=> feat: add warning for deprecated images

go.mod, go.sum, internal/helpers/helpers_cron.go, internal/helpers/helpers_cron_test.go
Just replaces the cron validation logic to use `robfig/cron` to do the final validation. This is what kubernetes uses under the hood in the cronjob controller.
Only the lagoon pseudo random seed replacements are performed and updates the schedule before handing off to be validated.
=> refactor: use robfigcron for validation after lagoon replacements

Dockerfile
Just changes up the `COPY . ./` in the dockerfile to copy in Go components only to try reduce cache invalidation
=> build: copy required go components to reduce cache invalidation

Dockerfile, legacy/build-deploy-docker-compose.sh
The `remote-controller` has the ability to inject any variables defined against it that start with `LAGOON_FEATURE_FLAG_` into build pods.
This sets the default documentation url to `https://docs.lagoon.sh` but allows for the remote-controller to override this
Adding `LAGOON_FEATURE_FLAG_DEFAULT_DOCUMENTATION_URL` with the url of the alternative documentation, this way references to documentation can point to a version suited for custom installations, as long as the alternative documentation paths are the same.
=> feat: allow documentation url to be changed

internal/generator/generator.go
In #360 we changed buildkit to be enabled by default, this still leaves buildkit as enabled by default, but allows for the `LAGOON_FEATURE_FLAG_(DEFAULT|FORCE)_X` variable in the remote to change this default. If a user has added the existing `DOCKER_BUILDKIT` variable, this is still used.
=> chore: add featureflag to change default buildkit setting

legacy/build-deploy-docker-compose.sh
Just a quick one to check that the secret of an ingress exists before trying to access it to verify if it needs to be deleted.
Also ensure that the name of the secret is correctly used, not with the `-tls` suffix, as this is already in the variable.
=> fix: check secret exists before trying to read or delete it

cmd/identify_imagebuild_test.go, internal/generator/helpers_generator.go, internal/generator/helpers_generator_test.go, internal/generator/services.go, internal/testdata/basic/docker-compose.forcebaseimagepull-2.yml, internal/testdata/basic/lagoon.forcebaseimagepull-2.yml
This PR extends #355 by adding the ability to specify tags with environment variables.
It allows the `lagoon.base.image` task to be populated with variables that can be provided to a project or environment and parse them during a lagoon build stage to calculate the required base image to pull.
Variable replacement is similar to `envplate`. They must be in the `${}` format, ie
```
lagoon.base.image: 'repo/image:${BASE_IMAGE_TAG}' 
lagoon.base.image: 'repo/image:${BASE_IMAGE_TAG:-main}'`
lagoon.base.image: '${BASE_IMAGE_REPO:-repo}/image:${BASE_IMAGE_TAG:-main}'`
```
Nested variables like `${BASE_IMAGE_TAG:-${OTHER_IMAGE_TAG:-latest}}` will not work.
=> feat: variable replacement support for lagoon.base.image label

internal/lagoon/fastly.go, internal/lagoon/fastly_test.go, internal/lagoon/routes.go
Just a minor quality of life improvement for AIO that the watch status used in the `LAGOON_FASTLY_SERVICE_ID(S)` variable is optional and will default to `true`.
=> fix: default fastly watch status to true if not provided in variable

legacy/build-deploy-docker-compose.sh
To help make #304 a reality, this is a phased approach to implement the failure that is detected if a docker-compose file has yaml errors that need to be addressed.
By default, this will make `development` type environments builds fail. It is possible to disable this error using the feature flags
```
LAGOON_FEATURE_FLAG_DEVELOPMENT_DOCKER_COMPOSE_VALIDATION=disabled
LAGOON_FEATURE_FLAG_DEFAULT_DEVELOPMENT_DOCKER_COMPOSE_VALIDATION=disabled
```
Production environments will continue to warn, but it is possible to enable the errors using feature flags
```
LAGOON_FEATURE_FLAG_PRODUCTION_DOCKER_COMPOSE_VALIDATION=enabled
LAGOON_FEATURE_FLAG_DEFAULT_PRODUCTION_DOCKER_COMPOSE_VALIDATION=enabled
```
Eventually though, the warnings will become failures with no way to disable the error as we …
=> feat: implement feature to fail builds on docker-compose yaml errors

internal/servicetypes/types.go, internal/servicetypes/valkey.go, internal/templating/services/templates_cronjob.go, internal/templating/services/templates_deployment.go, internal/templating/services/templates_deployment_test.go, internal/templating/services/test-resources/deployment/result-valkey-1.yaml
Adds a supporting `valkey` service type for the recently released Valkey images.
Currently the `redis` and `valkey` types are identical except for the name. But if the projects diverge further, or there are changes specific to Valkey that need to be made, the new type should be used.
This may be difficult for existing users that currently use the `redis` service types since changing types in Lagoon is not currently possible without significant effort. With #274 though, it would be possible to delete a `redis` service and create a new one called `valkey`. Persistent versions using this would experience data loss.
=> feat: add valkey service type

cmd/template_backups_test.go, internal/templating/template_schedule.go, internal/templating/template_schedule_test.go, internal/templating/test-resources/backups/test-k8up-v1-rootless-onrootmismatch.yaml, internal/templating/test-resources/backups/test-k8up-v1-rootless.yaml, internal/testdata/node/backup-templates/test-generic-backup-rootless-workloads-onrootmismatch/k8up-lagoon-backup-schedule.yaml, internal/testdata/node/backup-templates/test-generic-backup-rootless-workloads/k8up-lagoon-backup-schedule.yaml
Replaces #389 with a similar outcome. This is supported in older versions of k8up v2 though unlike `PodConfig`
closes #361
=> feat(fix): set runasuser podsecuritycontext for backup schedules

legacy/build-deploy-docker-compose.sh
We used to support custom deployment templates and rollouts under Openshift. I believe this code is some leftovers of that era that was not removed as part of an [old cleanup commit](https://github.com/uselagoon/lagoon/commit/3fdb17baee346f967bafd789f4992daca9cf53b1).
While it is still technically possible for a project to set the rollout type to `false`, and disable rollout monitoring for that service, I can't think of a valid reason why we should continue to support this.
Already have a PR to document it as deprecated https://github.com/uselagoon/lagoon/pull/3871.
=> fix: remove unused remnants of custom rollout support

Makefile
Changes the name of the built image to `lagoon/build-deploy-image:local` instead of just `build-deploy-image:local`, also some minor adjustments to the makefile.
=> chore: modify name of image built locally

go.mod, go.sum, internal/templating/template_registrysecret.go, internal/templating/template_registrysecret_test.go, internal/templating/test-resources/regsecret/registry-secret2.yaml
Fixes a bug in the registry secret generation that doesn't properly escape the payload. Now uses the docker authconfig type to create and json marshal function to convert to byte array for the secret.
=> fix: use docker library to create registry secret authconfig

internal/servicetypes/elasticsearch.go, internal/servicetypes/opensearch.go, internal/templating/test-resources/deployment/result-elasticsearch-1.yaml, internal/templating/test-resources/deployment/result-opensearch-1.yaml, internal/testdata/complex/service-templates/test-complex-persistent-names/deployment-opensearch.yaml, internal/testdata/complex/service-templates/test8-multiple-services/deployment-opensearch-2.yaml
With https://github.com/uselagoon/lagoon-charts/pull/700 we should be able to remove the `initContainer` that sets sysctl values with privileged access. 
The daemonset in the chart will do it instead, best yet would be the underlying k8s nodes having this value increased by default though.
=> chore: remove open/elasticsearch init container

go.mod, go.sum, internal/generator/services.go, internal/generator/services_test.go, internal/generator/volumes_test.go, internal/testdata/basic/service-templates/test10-basic-no-native-cronjobs/deployment-node.yaml, internal/testdata/basic/service-templates/test11-basic-polysite-cronjobs/deployment-node.yaml, internal/testdata/complex/service-templates/test2-nginx-php/deployment-cli.yaml, internal/testdata/complex/service-templates/test2b-nginx-php/deployment-cli.yaml, internal/testdata/complex/service-templates/test2c-nginx-php/deployment-cli.yaml, internal/testdata/complex/service-templates/test2d-nginx-php/deployment-cli.yaml
This change enforces that in-pod cronjobs have only one instance of the job running at any one time.
Specifically, this change fixes the issue where minutely cronjobs which take longer than a minute to run result in dozens of instances of the job running at the same time. In some cases this can cause Lagoon users to DoS themselves or use excessive CPU or memory resources.
Closes: https://github.com/uselagoon/lagoon-images/issues/172
=> fix: enforce only one instance of an in-pod cronjob running at once

cmd/template_backups_test.go, cmd/template_lagoonservices_test.go, internal/generator/generator.go, internal/testdata/complex/docker-compose.redis-persistent.yml, internal/testdata/complex/lagoon.redis-persistent.yml, internal/testdata/complex/service-templates/test-redis-persistent-k8upv2/deployment-redis.yaml, internal/testdata/complex/service-templates/test-redis-persistent-k8upv2/pvc-redis.yaml, internal/testdata/complex/service-templates/test-redis-persistent-k8upv2/service-redis.yaml
This fixes a bug with the check performed on which version of k8up should be used when adding annotations. Now correctly uses the feature flag.
=> fix: use the k8upv2 feature flag correctly

internal/lagoon/compose.go, internal/testdata/basic/docker-compose.yml
Passes in the compose service definition to verify the labels used now instead of checking yaml directly.
Adjusted one of the test case docker compose files to use the list for labels to ensure that the tests pass correctly for this other label format.
=> fix: use compose spec with servicename validity check for labels

legacy/build-deploy-docker-compose.sh
The escaping that was required for syaml is breaking the jq parsing in cases where projects have a period in the branch name
=> Removes extraneous escaping in jq

internal/templating/template_prebackuppod.go, internal/templating/test-resources/backups/result-prebackuppod1.yaml, internal/templating/test-resources/backups/result-prebackuppod2.yaml, internal/templating/test-resources/backups/result-prebackuppod3.yaml, internal/templating/test-resources/backups/result-prebackuppod4.yaml, internal/templating/test-resources/backups/result-prebackuppod5.yaml, internal/testdata/complex/backup-templates/backup-1/prebackuppods.yaml, internal/testdata/complex/backup-templates/backup-2/prebackuppods.yaml
In #397 we changed the `lagoon-env` configmap to secret. This fixes a missing change to prebackuppods that also sets this.
=> fix: use secretKeyRef in prebackuppods

internal/generator/generator.go, legacy/build-deploy-docker-compose.sh
This adds a simple retry logic to capture a weird buildkit related layer issue. While we're working to resolve the actual issue and understand the root cause, this retry logic should help to reduce the instance of failures encountered by forcing a subsequent build to build with the `--no-cache` flag.
=> refactor: add retry workaround for image builds

legacy/scripts/exec-generate-insights-configmap.sh
Extends insights labels to include the environment type (development/production) in the insights config maps.
=> Feature: Adds environment type to insights config maps

internal/generator/buildvalues.go, internal/generator/generator.go, internal/templating/templates_cronjob.go, internal/templating/templates_deployment.go
Refactor the automount service account token to allow for administratively enabling it via lagoon-remote only.
It is still disabled by default, and only the `ADMIN_LAGOON_FEATURE_FLAG_AUTOMOUNT_SERVICE_ACCOUNT_TOKEN=true` variable being added to the `lagoon-remote` or remote-controller will be able to enable this functionality.
=> refactor: disable automount with admin flag override

legacy/docker-entrypoint.sh
In the event that the dockerhost fails to connect and a build fails, instruct the user to retry. If it continues, contact support.
Usually this has been shows as a result of an intermittent network issue, but if it is persistent then there could be a problem with the docker-host that needs to be investigated by a platform operator.
=> chore: add retry message to dockerhost connection failure

internal/lagoon/tasks.go
The task scaling debug output contains a logic error in the output, showing `n` instead of `n - 1`
=> Better debugging output for task scaling

legacy/build-deploy-docker-compose.sh
Fixes where the lagoon yaml validation completion step prints in the log output to prevent it combining with the docker-compose validation step.
The issue is that the `STEP .lagoon.yml Validation: Completed` was being printed after the `BEGIN Docker Compose Validation` stage, when it should be before.
An example of the incorrect log is below:
```
##############################################
BEGIN .lagoon.yml Validation
##############################################
Updating lagoon-yaml configmap with a pre-deploy version of the .lagoon.yml file
configmap/lagoon-yaml configured
##############################################
BEGIN Docker Compose Validation
##############################################
Updating docker-compose-yaml configmap with a pre-deploy version of the …
```
=> fix: print lagoonyaml validation completion before dockercompose validation

legacy/build-deploy-docker-compose.sh
Small fix on top of #458 
The deletion of the cert-manager resource while the error was captured, still returned `exit 1`, this fixes it so that it won't return 1 on failure.
Additionally fixes an incorrect variable used.
=> fix: cert cleanup process

internal/templating/template_prebackuppod.go, internal/templating/test-resources/backups/result-prebackuppod1.yaml, internal/templating/test-resources/backups/result-prebackuppod2.yaml, internal/templating/test-resources/backups/result-prebackuppod4.yaml, internal/templating/test-resources/backups/result-prebackuppod5.yaml, internal/testdata/complex/backup-templates/backup-1/prebackuppods.yaml, internal/testdata/complex/backup-templates/backup-2/prebackuppods.yaml
This adds slashes to the end of command lines introduced in #451
=> fix: add slashes to backup commands
