- cmd/tasks_run.go
- internal/lagoon/tasks.go
> Fixes error output and task name visibility

- .goreleaser.yml
- Makefile
- cmd/root.go
Just a quick PR to add version information
> Command to view version information

- legacy/build-deploy-docker-compose.sh
Addresses Issue https://github.com/uselagoon/build-deploy-tool/issues/97
Replicated the `patchBuildStep` function and updated it so it outputs `BEGIN`.
Added the `beginBuildStep` function at the beginning of alll relevant sections.
Build Logs: [lagoon-build-26yr8j-57c54bee-5658-40b9-86dd-a0d82d36319c.txt](https://github.com/uselagoon/build-deploy-tool/files/9430191/lagoon-build-26yr8j-57c54bee-5658-40b9-86dd-a0d82d36319c.txt)
closes https://github.com/uselagoon/build-deploy-tool/issues/97
> First pass at adding section headers

- legacy/scripts/exec-backup-generation.sh
Just some adjustments to the backup generation script to fix some verbosity
> refactor: less verbose backup generation output

- legacy/build-deploy-docker-compose.sh
> fix: pre and post rollout disable variable checks

- internal/lagoon/tasks.go
> Increases verbosity of logging for task service and container

- legacy/build-deploy-docker-compose.sh
> feat: support ephemeral-storage limit on resource

- legacy/build-deploy-docker-compose.sh
Just a fix to actually apply the templates for routes after they're generated. PR #125 moved a step that would apply templates to after the routes are calculated. This meant that the API was not updated to reflect the routes generated, and the `lagoon-env` config-map was not updated either.
Fix is to just do the apply step before like it would have done before so that the calculation succeeds.
A build log break point is also moved into a more suitable location for image builds
> fix: route generation step and move the break point

- internal/generator/backups.go
- internal/generator/backups_test.go
- test-resources/template-backups/test1-results/k8up-lagoon-backup-schedule.yaml
- test-resources/template-backups/test2-results/k8up-lagoon-backup-schedule.yaml
- test-resources/template-backups/test3-results/k8up-lagoon-backup-schedule.yaml
- test-resources/template-backups/test4-results/k8up-lagoon-backup-schedule.yaml
- test-resources/template-backups/test5-results/k8up-lagoon-backup-schedule.yaml
- test-resources/template-backups/test6-results/k8up-lagoon-backup-schedule.yaml
> fix: change the default prune and check times to be different to reduce clashes

- legacy/helmcharts/redis-persistent/templates/deployment.yaml
> chore: set backup timeout to 14400 seconds

- legacy/scripts/exec-monitor-deploy.sh
Just refactors the pod rollout failure log capture to capture pods/container logs for the service that are not ready/running.
Previous version used a replicaset hash which didn't always capture the logs for the pods.
> refactor: pod rollout failure log capture

- legacy/build-deploy-docker-compose.sh
- legacy/scripts/exec-generate-insights-configmap.sh
combines #307 and a wrapper around the insights gathering to turn them into warnings
> refactor: make insights gathering step capture as warnings rather than build error

- internal/helpers/helpers_cron.go
- internal/helpers/helpers_cron_test.go
just another quick fix to inpod cronjob checks
> fix: trim cronjob inpod check

- internal/generator/container_registries.go
just fixes the container registry sorting to ensure known order for tests
> fix: sort container registries by name

- legacy/build-deploy-docker-compose.sh
- legacy/build-deploy.sh
- legacy/scripts/exec-kubectl-mariadb-dbaas.sh
- legacy/scripts/exec-kubectl-mongodb-dbaas.sh
- legacy/scripts/exec-kubectl-postgres-dbaas.sh
- legacy/scripts/exec-monitor-deploy.sh
- legacy/scripts/git-checkout-pull-merge.sh
- legacy/scripts/git-checkout-pull.sh
This removes the over used `set +x/-x` from the builds reducing the overall verbosity of a build log.
> fix: reduce verbosity in build

- internal/helpers/helpers_cron.go
- internal/helpers/helpers_cron_test.go
Just some logic fixes for cronjobs with hours that may be multiple ranges.
> fix: support for cron with dual hour ranges

- cmd/template_lagoonservices_test.go
- internal/templating/services/templates_deployment.go
- internal/templating/services/templates_deployment_test.go
- internal/templating/services/test-resources/deployment/result-nginx-1.yaml
- internal/testdata/complex/service-templates/test2d-nginx-php/cronjob-cronjob-cli-drush-cron2.yaml
- internal/testdata/complex/service-templates/test2d-nginx-php/deployment-cli.yaml
- internal/testdata/complex/service-templates/test2d-nginx-php/deployment-nginx-php.yaml
- internal/testdata/complex/service-templates/test2d-nginx-php/deployment-redis.yaml
- internal/testdata/complex/service-templates/test2d-nginx-php/deployment-varnish.yaml
- internal/testdata/complex/service-templates/test2d-nginx-php/pvc-nginx-php.yaml
- internal/testdata/complex/service-templates/test2d-nginx-php/service-nginx-php.yaml
- internal/testdata/complex/service-templates/test2d-nginx-php/service-redis.yaml
- internal/testdata/complex/service-templates/test2d-nginx-php/service-varnish.yaml
Fixes the missing limits on linked containers
closes #391
> fix: add resources limits to linked container as required

- cmd/template_lagoonservices_test.go
- internal/templating/services/templates_deployment.go
- internal/templating/services/templates_deployment_test.go
- internal/templating/services/test-resources/deployment/result-nginx-1.yaml
- internal/testdata/complex/service-templates/test2d-nginx-php/cronjob-cronjob-cli-drush-cron2.yaml
- internal/testdata/complex/service-templates/test2d-nginx-php/deployment-cli.yaml
- internal/testdata/complex/service-templates/test2d-nginx-php/deployment-nginx-php.yaml
- internal/testdata/complex/service-templates/test2d-nginx-php/deployment-redis.yaml
- internal/testdata/complex/service-templates/test2d-nginx-php/deployment-varnish.yaml
- internal/testdata/complex/service-templates/test2d-nginx-php/pvc-nginx-php.yaml
- internal/testdata/complex/service-templates/test2d-nginx-php/service-nginx-php.yaml
- internal/testdata/complex/service-templates/test2d-nginx-php/service-redis.yaml
- internal/testdata/complex/service-templates/test2d-nginx-php/service-varnish.yaml
> chore: backport linked memory to pr379

- internal/templating/template_dbaas.go
- internal/templating/template_dbaas_test.go
- internal/templating/template_helpers.go
- internal/templating/template_networkpolicy.go
- internal/templating/template_networkpolicy_test.go
- internal/templating/template_prebackuppod.go
- internal/templating/template_prebackuppod_test.go
- internal/templating/template_registrysecret.go
- internal/templating/template_registrysecret_test.go
- internal/templating/template_schedule.go
- internal/templating/template_schedule_test.go
- internal/templating/templates_cronjob.go
- internal/templating/templates_cronjob_test.go
- internal/templating/templates_deployment.go
- internal/templating/templates_deployment_test.go
- internal/templating/templates_ingress.go
- internal/templating/templates_ingress_test.go
- internal/templating/templates_pvc.go
- internal/templating/templates_pvc_test.go
- internal/templating/templates_service.go
- internal/templating/templates_service_test.go
Fix the templating package name from #401
> fix: package name

- internal/lagoon/lagoon_test.go
- internal/lagoon/test-resources/lagoon-yaml/test9/polysite-only-lagoon.yml
> test: add polysite cronjob tests

- legacy/build-deploy-docker-compose.sh
As with #408 this removes another unused remnant
> fix: remove unused DEPLOY_TYPE variable

- legacy/build-deploy-docker-compose.sh
> refactor: buildkit failed to get layer

- internal/lagoon/tasks.go
We've experienced a few instances where a post-rollout task seems to hang. This is _very_ infrequent, and difficult to replicate. However, the function we're using to exec in the pods has been deprecated and it would be useful to have _slightly_ more info about the running of the post-rollout task itself.
This PR addresses both of these.
> Fixes deprecated call, adds slightly more debugging info

- internal/templating/templates_cronjob.go
- internal/templating/templates_cronjob_test.go
- internal/templating/templates_deployment.go
- internal/templating/templates_deployment_test.go
Sure @shreddedbacon - here's my PR related to the #447 PR, with the error handling and a couple of associated tests.
> fix: Deployment (and cronjob) template error handling

- legacy/build-deploy-docker-compose.sh
Small fix/refactor to clean up certificates when an ingress is deleted
> fix: clean up certificates when ingress are deleted
